// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteLibrary.Models.Contexts;

namespace NoteLibrary.Migrations
{
    [DbContext(typeof(NoteContext))]
    [Migration("20181213201458_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoteLibrary.Models.Entities.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriesIDID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("State");

                    b.HasKey("ID");

                    b.HasIndex("CategoriesIDID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("NoteLibrary.Models.Entities.Categories", b =>
                {
                    b.HasOne("NoteLibrary.Models.Entities.Categories", "CategoriesID")
                        .WithMany()
                        .HasForeignKey("CategoriesIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
